RAG Pipeline
r
r: failed to push some refs to
'https://github.com/jihangh/RAG-based-Medical-Chatbot.git'
hint: Updates were rejected because the remote contains work that you do
not
hint: have locally. This is usually caused by another repository pushing
to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for
details.

C:\Users\OMEN\Desktop\RAG Project\Medical-Chatbot-Fastapi>git pull
origin main --rebase
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (3/3), 4.67 KiB | 227.00 KiB/s, done.
From https://github.com/jihangh/RAG-based-Medical-Chatbot
 * branch            main       -> FETCH_HEAD
  + 3237fb3...c336ac8 main       -> origin/main  (forced update)
  CONFLICT (modify/delete): .gitignore deleted in HEAD and modified in
  41b047d (RAG Pipeline).  Version 41b047d (RAG Pipeline) of .gitignore
  left in tree.
  CONFLICT (modify/delete): README.md deleted in HEAD and modified in
  41b047d (RAG Pipeline).  Version 41b047d (RAG Pipeline) of README.md
  left in tree.
  CONFLICT (modify/delete): app/config/config.yaml deleted in HEAD and
  modified in 41b047d (RAG Pipeline).  Version 41b047d (RAG Pipeline) of
  app/config/config.yaml left in tree.
  CONFLICT (modify/delete): app/services/vector_db/build_vector_store.py
  deleted in HEAD and modified in 41b047d (RAG Pipeline).  Version
  41b047d (RAG Pipeline) of app/services/vector_db/build_vector_store.py
  left in tree.
  CONFLICT (modify/delete): assets/demo_screenshot0.PNG deleted in HEAD
  and modified in 41b047d (RAG Pipeline).  Version 41b047d (RAG
  Pipeline) of assets/demo_screenshot0.PNG left in tree.
  error: could not apply 41b047d... RAG Pipeline
  hint: Resolve all conflicts manually, mark them as resolved with
  hint: "git add/rm <conflicted_files>", then run "git rebase
  --continue".
  hint: You can instead skip this commit: run "git rebase --skip".
  hint: To abort and get back to the state before "git rebase", run "git
  rebase --abort".
  #       new file:   app/schemas/__init__.py
  #       new file:   app/schemas/rag_schema.py
  #       new file:   app/services/embedding_generation/ensure_embed.py
  #       new file:   app/services/ragchain/__init__.py
  #       new file:   app/services/vector_db/build_vector_store.py
  #       new file:   app/services/vector_db/ensure_vector.py
  #       new file:   app/utils/chunks_cache.py
  #       new file:   app/utils/fingerprint.py
  #       new file:   app/utils/state_loader.py
  #       new file:   assets/demo_screenshot0.PNG
  #       new file:   main.py

  #
  .git/COMMIT_EDITMSG[+] [unix] (09:38 01/02/2026)
  26,1 Bot-- INSERT --

  :wq